In [31]:
"""""
BDM 200 Final Project.
News Recommender System
Goal: Computing Euclidean similarity to find the most similar articles. 
"""""
import pandas as pd
import numpy as np
from collections import Counter

#Reading the article vectors
articles_df = pd.read_excel('news_vectors (1).xlsx')

# Convert to numpy array 
articles_vectors = articles_df.values
num_articles = articles_vectors.shape[0]

# Initialize similarity matrix (1000x1000)
similarity_matrix = np.zeros((num_articles,num_articles))

# Compute Euclidean Similarity between each pair of vectors
for i in range(num_articles):
    for j in range(num_articles):
        # Calculate dot product as similarity measure
        similarity_matrix[i, j] = np.dot(articles_vectors[i], articles_vectors[j])

most_similar_list = []

for i in range(num_articles):
    similarities = similarity_matrix[i].copy()
    similarities[i] = -1  # Exclude itself
    most_similar_idx = np.argmax(similarities)
    most_similar_list.append(most_similar_idx)
    
print("Results saved to 'result.txt'")

# Save results to a text file
with open("result.txt", "w") as f:
    f.write("Article, Most Similar Article\n")
    for i in range(num_articles):
        f.write(f"s{i+1}, s{most_similar_list[i]+1}\n")

# Print the top-left 5x5 section of the similarity matrix
print("\nSample of Similarity Matrix (top-left 5x5):")
print(similarity_matrix[:5, :5])

# Sample of results
print("\nSample of results (first 10 articles):")
for i in range(10):
    print(f"s{i+1} is most similar to s{most_similar_list[i]+1}")

# Counting the frequency
counter = Counter(most_similar_list)

# Printing the Articles with the most common similarities (Top 10)
print("\nArticle with the most common similarities: ")
for article_idx, count in counter.most_common(10):
    print(f"s{article_idx+1}: {count} article")
    

Results saved to 'result.txt'

Sample of Similarity Matrix (top-left 5x5):
[[0.71649597 0.42894432 0.36223582 0.70221699 0.68791811]
 [0.42894432 0.42611734 0.25133579 0.42258736 0.42945068]
 [0.36223582 0.25133579 0.19280851 0.35556883 0.35149966]
 [0.70221699 0.42258736 0.35556883 0.68874162 0.67473406]
 [0.68791811 0.42945068 0.35149966 0.67473406 0.66279983]]

Sample of results (first 10 articles):
s1 is most similar to s507
s2 is most similar to s507
s3 is most similar to s507
s4 is most similar to s507
s5 is most similar to s507
s6 is most similar to s559
s7 is most similar to s507
s8 is most similar to s507
s9 is most similar to s507
s10 is most similar to s507

Article with the most common similarities: 
s507: 603 article
s559: 387 article
s533: 3 article
s918: 2 article
s360: 1 article
s902: 1 article
s414: 1 article
s72: 1 article
s754: 1 article
